name: polis
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  intl: ^0.16.1
  flutter_bloc: ^4.0.1
  bloc: ^4.0.0
  simple_router: ^0.1.0+1
  equatable: ^1.2.0
  json_serializable: ^3.3.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.2
  shared_preferences: ^0.5.7+3
  image_picker: ^0.6.7+2
  url_launcher: ^5.4.11
  flutter_native_admob: ^2.1.0

  # Utils
  diacritic: ^0.1.1
  uuid: ^2.1.0
  tuple: ^1.0.3
  screenshot: ^0.2.0
  esys_flutter_share: ^1.0.2
  in_app_update: ^1.1.11
  flutter_bloc_monitor: ^1.0.0+1

  # Firebase
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.2
  firebase_messaging: ^6.0.16

  # UI
  fancy_shimmer_image: ^1.0.1
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.8.1
  smart_select: ^3.0.3
  flutter_grid_delegate_ext: ^0.0.2
  sliding_panel: ^1.0.3
  skeleton_text: ^1.0.0
  flare_flutter: ^2.0.4
  flutter_spinkit: ^4.1.2+1
  expandable_bottom_sheet: ^0.2.1+1
  lite_rolling_switch: ^0.1.1

dependency_overrides:
  dartx: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Generators
  build_runner:
  hive_generator: ^0.7.0+2

  # Tests
  test: ^1.14.4
  bloc_test: ^5.1.0
  mockito: ^4.1.1
  image_test_utils:
    git: 'https://github.com/MarcinusX/image_test_utils'

  # Linting
  effective_dart: ^1.2.3

  # Helper
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  image: 'assets/images/splash_foreground.png'
  color: '#000000'
  android_disable_fullscreen: true

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/images/plogo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher/Philosopher-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
